"""Extended per-system metadata keyed by canonical system ID."""

from __future__ import annotations

from typing import Any

SYSTEM_METADATA: dict[str, dict[str, Any]] = {
    "sys-agt-refund-001": {
        "archetype": "decision",
        "description": "Evaluates refund requests and decides approve, reject, or escalate.",
        "business_function": "payments",
        "cloud_provider": "aws",
        "cloud_service": "bedrock",
        "cloud_region": "us-east-1",
        "model_provider": "aws.bedrock",
        "approved_model_name": "claude-3-5-sonnet",
        "approved_model_version": "20241022-v2",
        "approved_regions": ("us-east-1",),
        "approved_tools": ("policy_lookup", "refund_execute", "customer_lookup"),
        "blocked_tools": ("wire_transfer",),
        "data_sensitivity": "confidential",
        "supported_scenarios": ("approval_threshold_bypass", "excessive_tool_retries"),
    },
    "sys-agt-cs-002": {
        "archetype": "security_operations",
        "description": "Classifies support requests and routes to teams or tools.",
        "business_function": "customer_support",
        "cloud_provider": "azure",
        "cloud_service": "azure_openai",
        "cloud_region": "eastus",
        "model_provider": "azure.ai.openai",
        "approved_model_name": "gpt-4o",
        "approved_model_version": "2024-11",
        "approved_regions": ("eastus",),
        "approved_tools": ("route_queue", "customer_lookup"),
        "blocked_tools": ("admin_console",),
        "data_sensitivity": "internal",
        "supported_scenarios": ("provider_latency_regression", "excessive_tool_retries"),
    },
    "sys-agt-pep-003": {
        "archetype": "decision",
        "description": "Screens individuals against PEP and sanctions evidence.",
        "business_function": "compliance",
        "cloud_provider": "gcp",
        "cloud_service": "vertex_ai",
        "cloud_region": "us-central1",
        "model_provider": "gcp.vertex_ai",
        "approved_model_name": "gemini-1.5-pro",
        "approved_model_version": "2026-01",
        "approved_regions": ("us-central1",),
        "approved_tools": ("watchlist_search", "escalation_queue"),
        "blocked_tools": (),
        "data_sensitivity": "restricted",
        "supported_scenarios": ("grounding_score_drop",),
    },
    "sys-agt-kyc-004": {
        "archetype": "document",
        "description": "Extracts and validates customer identity documents.",
        "business_function": "onboarding",
        "cloud_provider": "aws",
        "cloud_service": "bedrock",
        "cloud_region": "us-east-1",
        "model_provider": "aws.bedrock",
        "approved_model_name": "claude-3-5-sonnet",
        "approved_model_version": "20241022-v2",
        "approved_regions": ("us-east-1",),
        "approved_tools": ("ocr_extract", "case_write"),
        "blocked_tools": (),
        "data_sensitivity": "restricted",
        "supported_scenarios": ("sensitive_data_exposure",),
    },
    "sys-agt-inv-005": {
        "archetype": "document",
        "description": "Extracts invoice fields and validates against PO data.",
        "business_function": "accounts_payable",
        "cloud_provider": "azure",
        "cloud_service": "azure_openai",
        "cloud_region": "eastus",
        "model_provider": "azure.ai.openai",
        "approved_model_name": "gpt-4o",
        "approved_model_version": "2024-11",
        "approved_regions": ("eastus",),
        "approved_tools": ("po_validate", "erp_write"),
        "blocked_tools": (),
        "data_sensitivity": "internal",
        "supported_scenarios": (),
    },
    "sys-agt-treasury-001": {
        "archetype": "retrieval_grounded",
        "description": "Generates treasury commentary using market data and governed sources.",
        "business_function": "treasury",
        "cloud_provider": "gcp",
        "cloud_service": "vertex_ai",
        "cloud_region": "us-central1",
        "model_provider": "gcp.vertex_ai",
        "approved_model_name": "gemini-1.5-pro",
        "approved_model_version": "2026-01",
        "fallback_provider": "azure.ai.openai",
        "approved_regions": ("us-central1", "eastus"),
        "approved_tools": ("market_data_lookup", "policy_context_retrieval", "citation_service"),
        "blocked_tools": (),
        "data_sensitivity": "internal_confidential",
        "supported_scenarios": ("unsupported_claim_spike",),
    },
    "sys-agt-rag-007": {
        "archetype": "retrieval_grounded",
        "description": "Answers employee questions from internal knowledge sources.",
        "business_function": "knowledge",
        "cloud_provider": "aws",
        "cloud_service": "bedrock",
        "cloud_region": "us-east-1",
        "model_provider": "aws.bedrock",
        "approved_model_name": "claude-3-5-sonnet",
        "approved_model_version": "20241022-v2",
        "approved_regions": ("us-east-1",),
        "approved_tools": ("doc_retrieval", "permission_filter"),
        "blocked_tools": (),
        "data_sensitivity": "internal",
        "supported_scenarios": ("retrieval_degradation",),
    },
    "sys-agt-phish-008": {
        "archetype": "security_operations",
        "description": "Analyzes suspicious messages for quarantine or escalation.",
        "business_function": "security",
        "cloud_provider": "azure",
        "cloud_service": "azure_openai",
        "cloud_region": "eastus",
        "model_provider": "azure.ai.openai",
        "approved_model_name": "gpt-4o",
        "approved_model_version": "2024-11",
        "approved_regions": ("eastus",),
        "approved_tools": ("quarantine_route", "ti_lookup"),
        "blocked_tools": ("refund_api_execute", "admin_console"),
        "data_sensitivity": "confidential",
        "supported_scenarios": ("tool_scope_violation", "prompt_injection_attempt"),
    },
    "sys-agt-access-009": {
        "archetype": "decision",
        "description": "Reviews user access and recommends approval or revocation.",
        "business_function": "identity",
        "cloud_provider": "aws",
        "cloud_service": "bedrock",
        "cloud_region": "us-east-1",
        "model_provider": "aws.bedrock",
        "approved_model_name": "claude-3-5-sonnet",
        "approved_model_version": "20241022-v2",
        "approved_regions": ("us-east-1",),
        "approved_tools": ("entitlement_lookup", "access_change"),
        "blocked_tools": (),
        "data_sensitivity": "restricted",
        "supported_scenarios": ("unapproved_region_invocation",),
    },
    "sys-agt-reg-010": {
        "archetype": "retrieval_grounded",
        "description": "Monitors regulatory sources and produces impact assessments.",
        "business_function": "compliance",
        "cloud_provider": "gcp",
        "cloud_service": "vertex_ai",
        "cloud_region": "europe-west1",
        "model_provider": "gcp.vertex_ai",
        "approved_model_name": "gemini-1.5-pro",
        "approved_model_version": "2026-01",
        "approved_regions": ("europe-west1",),
        "approved_tools": ("reg_source_poll", "impact_analysis"),
        "blocked_tools": (),
        "data_sensitivity": "internal",
        "supported_scenarios": ("missing_runtime_logging",),
    },
}


def metadata_for(system_id: str) -> dict[str, Any]:
    return SYSTEM_METADATA.get(system_id, {"archetype": "decision"})
