"""Mock integrations configured on Fleetrac's control plane.

These provide the Integrations surface in Settings. The set is intentionally
broad (cloud, data platforms, model providers, observability, ticketing,
workflow, model registry) so the page feels like a real enterprise
connection footprint.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

from app.schemas.operations import Integration


def _ts(hours_ago: int, minutes: int = 0) -> datetime:
    return datetime.now(timezone.utc) - timedelta(hours=hours_ago, minutes=minutes)


INTEGRATIONS: list[Integration] = [
    Integration(
        id="int_aws",
        provider="AWS",
        kind="cloud",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "sandbox"],
        telemetry_availability="full",
        config_access="read_only",
        action_scope="read_only",
        last_sync=_ts(0, 12),
        note="Primary cloud. Read-only IAM role used for config and log ingest.",
        capabilities=["cloudwatch_logs", "s3_artifact_registry", "bedrock_metadata"],
    ),
    Integration(
        id="int_azure",
        provider="Azure",
        kind="cloud",
        connection_status="connected",
        auth_status="token_expiring",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="full",
        config_access="read_only",
        action_scope="read_only",
        last_sync=_ts(0, 27),
        note="Service principal token renews in 9 days.",
        capabilities=["monitor_logs", "azure_openai_metadata"],
    ),
    Integration(
        id="int_gcp",
        provider="GCP",
        kind="cloud",
        connection_status="degraded",
        auth_status="ok",
        sync_status="delayed",
        connector_type="api",
        environments=["production"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="read_only",
        last_sync=_ts(3, 41),
        note="Cloud Logging export is running ~3h behind. Fleetrac is treating affected telemetry as partial.",
        capabilities=["cloud_logging", "vertex_metadata"],
    ),
    Integration(
        id="int_databricks",
        provider="Databricks",
        kind="data_platform",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "sandbox"],
        telemetry_availability="full",
        config_access="read_only",
        action_scope="prepare_only",
        last_sync=_ts(0, 8),
        note="Used for retrieval pipeline telemetry and feature freshness checks.",
        capabilities=["jobs_metadata", "model_serving_metrics", "mlflow_registry"],
    ),
    Integration(
        id="int_snowflake",
        provider="Snowflake",
        kind="data_platform",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production"],
        telemetry_availability="metadata_only",
        config_access="none",
        action_scope="none",
        last_sync=_ts(1, 3),
        note="Read-only service account scoped to governance views.",
        capabilities=["governance_views", "query_history_sample"],
    ),
    Integration(
        id="int_openai",
        provider="OpenAI",
        kind="model_provider",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="none",
        action_scope="read_only",
        last_sync=_ts(0, 3),
        note="Usage and latency metadata only. No prompt/response payloads ingested.",
        capabilities=["usage_metrics", "model_deprecation_feed"],
    ),
    Integration(
        id="int_azure_openai",
        provider="Azure OpenAI",
        kind="model_provider",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="prepare_only",
        last_sync=_ts(0, 15),
        note="Primary regulated-workload model provider.",
        capabilities=["deployment_metadata", "usage_metrics", "content_filter_status"],
    ),
    Integration(
        id="int_anthropic",
        provider="Anthropic",
        kind="model_provider",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="none",
        action_scope="read_only",
        last_sync=_ts(0, 22),
        note="Used for comparative evaluation workflows.",
        capabilities=["usage_metrics"],
    ),
    Integration(
        id="int_vertex",
        provider="Vertex AI",
        kind="model_provider",
        connection_status="degraded",
        auth_status="ok",
        sync_status="delayed",
        connector_type="api",
        environments=["production"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="read_only",
        last_sync=_ts(2, 51),
        note="Downstream of GCP connector — inherits its ~3h ingest delay.",
        capabilities=["model_metadata", "endpoint_status"],
    ),
    Integration(
        id="int_bedrock",
        provider="AWS Bedrock",
        kind="model_provider",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="read_only",
        last_sync=_ts(0, 18),
        note="Cross-account role. Model inventory + invocation usage only.",
        capabilities=["foundation_model_inventory", "invocation_usage"],
    ),
    Integration(
        id="int_internal_model_api",
        provider="Internal Model APIs",
        kind="internal_model_api",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="sidecar",
        environments=["production", "staging", "sandbox", "internal_only"],
        telemetry_availability="full",
        config_access="read_write",
        action_scope="approval_gated",
        last_sync=_ts(0, 2),
        note="Fleetrac sidecar deployed alongside internal serving fabric.",
        capabilities=["config_read_write", "threshold_staging", "traffic_routing"],
    ),
    Integration(
        id="int_splunk",
        provider="Splunk",
        kind="observability",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="log_stream",
        environments=["production", "staging"],
        telemetry_availability="full",
        config_access="none",
        action_scope="none",
        last_sync=_ts(0, 4),
        note="Primary log stream source for regulated workloads.",
        capabilities=["log_stream", "saved_searches"],
    ),
    Integration(
        id="int_datadog",
        provider="Datadog",
        kind="observability",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "sandbox"],
        telemetry_availability="full",
        config_access="none",
        action_scope="read_only",
        last_sync=_ts(0, 5),
        note="Metrics, traces and synthetic checks.",
        capabilities=["metrics", "traces", "synthetics"],
    ),
    Integration(
        id="int_jira",
        provider="Jira",
        kind="ticketing",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "sandbox", "internal_only"],
        telemetry_availability="none",
        config_access="none",
        action_scope="limited_execution",
        last_sync=_ts(0, 6),
        note="Fleetrac may open governance tickets with a pre-approved template.",
        capabilities=["ticket_create", "status_sync"],
    ),
    Integration(
        id="int_servicenow",
        provider="ServiceNow",
        kind="ticketing",
        connection_status="needs_auth",
        auth_status="expired",
        sync_status="paused",
        connector_type="api",
        environments=["production"],
        telemetry_availability="none",
        config_access="none",
        action_scope="none",
        last_sync=_ts(72, 0),
        note="Credentials expired. Ticket creation falls back to Jira until re-authorized.",
        capabilities=["ticket_create"],
    ),
    Integration(
        id="int_airflow",
        provider="Apache Airflow",
        kind="workflow",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="prepare_only",
        last_sync=_ts(0, 9),
        note="Workflow diagnostic runs can be prepared for owner approval.",
        capabilities=["dag_metadata", "task_history"],
    ),
    Integration(
        id="int_argo",
        provider="Argo Workflows",
        kind="workflow",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="prepare_only",
        last_sync=_ts(0, 13),
        note="Runbook execution traces.",
        capabilities=["workflow_metadata"],
    ),
    Integration(
        id="int_mlflow",
        provider="MLflow Registry",
        kind="model_registry",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "sandbox"],
        telemetry_availability="metadata_only",
        config_access="read_only",
        action_scope="prepare_only",
        last_sync=_ts(0, 11),
        note="Version + tag metadata. Rollback targets resolved here.",
        capabilities=["model_versions", "tags", "stage_transitions"],
    ),
]
