"""Mock integrations configured on Fleetrac's control plane.

These provide the Integrations surface in Settings. The set is intentionally
broad (cloud, data platforms, model providers, observability, ticketing,
workflow, model registry) so the page feels like a real enterprise
connection footprint.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

from app.schemas.operations import (
    Integration,
    IntegrationActivity,
    IntegrationAuditLine,
)


def _ts(hours_ago: int, minutes: int = 0) -> datetime:
    return datetime.now(timezone.utc) - timedelta(hours=hours_ago, minutes=minutes)


INTEGRATIONS: list[Integration] = [
    Integration(
        id="int_aws",
        provider="AWS",
        kind="cloud",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "sandbox"],
        telemetry_availability="full",
        config_access="read_only",
        action_scope="read_only",
        last_sync=_ts(0, 12),
        note="Primary cloud. Read-only IAM role used for config and log ingest.",
        capabilities=["cloudwatch_logs", "s3_artifact_registry", "bedrock_metadata"],
        provider_key="aws",
        granted_scopes=[
            "cloudwatch:Describe*",
            "logs:FilterLogEvents",
            "logs:StartQuery",
            "s3:GetObject",
            "bedrock:ListFoundationModels",
        ],
        downstream_endpoints=[
            "CloudWatch Logs (us-east-1)",
            "S3 governance artifact bucket",
        ],
        activity_log=[
            IntegrationActivity(
                at=_ts(0, 12),
                message="Incremental log partition sync completed.",
                level="info",
            ),
            IntegrationActivity(
                at=_ts(2, 0),
                message="Bedrock model inventory refresh OK.",
                level="info",
            ),
        ],
        audit_log=[
            IntegrationAuditLine(
                at=_ts(720, 0),
                actor="Platform Engineering",
                summary="Rotated read-only IAM role credentials.",
            ),
        ],
        bob_prepare_actions=True,
        bob_execute_after_approval=False,
    ),
    Integration(
        id="int_azure",
        provider="Azure",
        kind="cloud",
        connection_status="connected",
        auth_status="token_expiring",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="full",
        config_access="read_only",
        action_scope="read_only",
        last_sync=_ts(0, 27),
        note="Service principal token renews in 9 days.",
        capabilities=["monitor_logs", "azure_openai_metadata"],
    ),
    Integration(
        id="int_gcp",
        provider="GCP",
        kind="cloud",
        connection_status="degraded",
        auth_status="ok",
        sync_status="delayed",
        connector_type="api",
        environments=["production"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="read_only",
        last_sync=_ts(3, 41),
        note="Cloud Logging export is running ~3h behind. Fleetrac is treating affected telemetry as partial.",
        capabilities=["cloud_logging", "vertex_metadata"],
    ),
    Integration(
        id="int_databricks",
        provider="Databricks",
        kind="data_platform",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "sandbox"],
        telemetry_availability="full",
        config_access="read_only",
        action_scope="prepare_only",
        last_sync=_ts(0, 8),
        note="Used for retrieval pipeline telemetry and feature freshness checks.",
        capabilities=["jobs_metadata", "model_serving_metrics", "mlflow_registry"],
    ),
    Integration(
        id="int_snowflake",
        provider="Snowflake",
        kind="data_platform",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production"],
        telemetry_availability="metadata_only",
        config_access="none",
        action_scope="none",
        last_sync=_ts(1, 3),
        note="Read-only service account scoped to governance views.",
        capabilities=["governance_views", "query_history_sample"],
    ),
    Integration(
        id="int_openai",
        provider="OpenAI",
        kind="model_provider",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="none",
        action_scope="read_only",
        last_sync=_ts(0, 3),
        note="Usage and latency metadata only. No prompt/response payloads ingested.",
        capabilities=["usage_metrics", "model_deprecation_feed"],
    ),
    Integration(
        id="int_azure_openai",
        provider="Azure OpenAI",
        kind="model_provider",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="prepare_only",
        last_sync=_ts(0, 15),
        note="Primary regulated-workload model provider.",
        capabilities=["deployment_metadata", "usage_metrics", "content_filter_status"],
    ),
    Integration(
        id="int_anthropic",
        provider="Anthropic",
        kind="model_provider",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="none",
        action_scope="read_only",
        last_sync=_ts(0, 22),
        note="Used for comparative evaluation workflows.",
        capabilities=["usage_metrics"],
    ),
    Integration(
        id="int_vertex",
        provider="Vertex AI",
        kind="model_provider",
        connection_status="degraded",
        auth_status="ok",
        sync_status="delayed",
        connector_type="api",
        environments=["production"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="read_only",
        last_sync=_ts(2, 51),
        note="Downstream of GCP connector — inherits its ~3h ingest delay.",
        capabilities=["model_metadata", "endpoint_status"],
    ),
    Integration(
        id="int_bedrock",
        provider="AWS Bedrock",
        kind="model_provider",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="read_only",
        last_sync=_ts(0, 18),
        note="Cross-account role. Model inventory + invocation usage only.",
        capabilities=["foundation_model_inventory", "invocation_usage"],
    ),
    Integration(
        id="int_internal_model_api",
        provider="Internal Model APIs",
        kind="internal_model_api",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="sidecar",
        environments=["production", "staging", "sandbox", "internal_only"],
        telemetry_availability="full",
        config_access="read_write",
        action_scope="approval_gated",
        last_sync=_ts(0, 2),
        note="Fleetrac sidecar deployed alongside internal serving fabric.",
        capabilities=["config_read_write", "threshold_staging", "traffic_routing"],
    ),
    Integration(
        id="int_splunk",
        provider="Splunk",
        kind="observability",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="log_stream",
        environments=["production", "staging"],
        telemetry_availability="full",
        config_access="none",
        action_scope="none",
        last_sync=_ts(0, 4),
        note="Primary log stream source for regulated workloads.",
        capabilities=["log_stream", "saved_searches"],
    ),
    Integration(
        id="int_datadog",
        provider="Datadog",
        kind="observability",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "sandbox"],
        telemetry_availability="full",
        config_access="none",
        action_scope="read_only",
        last_sync=_ts(0, 5),
        note="Metrics, traces and synthetic checks.",
        capabilities=["metrics", "traces", "synthetics"],
    ),
    Integration(
        id="int_jira",
        provider="Jira",
        kind="ticketing",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "sandbox", "internal_only"],
        telemetry_availability="none",
        config_access="none",
        action_scope="limited_execution",
        last_sync=_ts(0, 6),
        note="Fleetrac may open governance tickets with a pre-approved template.",
        capabilities=["ticket_create", "status_sync"],
        provider_key="jira",
        granted_scopes=[
            "jira:issue:create",
            "jira:issue:read",
            "jira:project:read",
            "jira:webhook:receive",
        ],
        downstream_endpoints=["Jira Cloud · AI-Governance project"],
        activity_log=[
            IntegrationActivity(
                at=_ts(0, 6),
                message="Ticket sync · 14 issues reconciled.",
                level="info",
            ),
            IntegrationActivity(
                at=_ts(5, 0),
                message="Bob handoff template v3 published to Jira.",
                level="info",
            ),
        ],
        bob_prepare_actions=True,
        bob_execute_after_approval=True,
    ),
    Integration(
        id="int_servicenow",
        provider="ServiceNow",
        kind="ticketing",
        connection_status="needs_auth",
        auth_status="expired",
        sync_status="paused",
        connector_type="api",
        environments=["production"],
        telemetry_availability="none",
        config_access="none",
        action_scope="none",
        last_sync=_ts(72, 0),
        note="Credentials expired. Ticket creation falls back to Jira until re-authorized.",
        capabilities=["ticket_create"],
        provider_key="servicenow",
        granted_scopes=["sn_incident.read", "sn_incident.write"],
        failure_notes=[
            "OAuth refresh failed: refresh token revoked in ServiceNow instance.",
            "Last successful sync was 72h ago; outbound change requests are paused.",
        ],
        activity_log=[
            IntegrationActivity(
                at=_ts(72, 0),
                message="Scheduled sync skipped — auth expired.",
                level="error",
            ),
            IntegrationActivity(
                at=_ts(73, 0),
                message="Retry scheduled after credential renewal.",
                level="warn",
            ),
        ],
        audit_log=[
            IntegrationAuditLine(
                at=_ts(168, 0),
                actor="Security Operations",
                summary="Scoped API user to incident table only.",
            ),
        ],
        bob_prepare_actions=False,
        bob_execute_after_approval=False,
    ),
    Integration(
        id="int_airflow",
        provider="Apache Airflow",
        kind="workflow",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="prepare_only",
        last_sync=_ts(0, 9),
        note="Workflow diagnostic runs can be prepared for owner approval.",
        capabilities=["dag_metadata", "task_history"],
    ),
    Integration(
        id="int_argo",
        provider="Argo Workflows",
        kind="workflow",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="read_only",
        action_scope="prepare_only",
        last_sync=_ts(0, 13),
        note="Runbook execution traces.",
        capabilities=["workflow_metadata"],
    ),
    Integration(
        id="int_mlflow",
        provider="MLflow Registry",
        kind="model_registry",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "sandbox"],
        telemetry_availability="metadata_only",
        config_access="read_only",
        action_scope="prepare_only",
        last_sync=_ts(0, 11),
        note="Version + tag metadata. Rollback targets resolved here.",
        capabilities=["model_versions", "tags", "stage_transitions"],
        provider_key="mlflow",
        bob_prepare_actions=True,
        bob_execute_after_approval=False,
    ),
    Integration(
        id="int_slack",
        provider="Slack",
        kind="collaboration",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging", "internal_only"],
        telemetry_availability="none",
        config_access="none",
        action_scope="limited_execution",
        last_sync=_ts(0, 2),
        note="Governance notifications and human-in-the-loop approvals in #ai-governance.",
        capabilities=[
            "notify_owner_channel",
            "post_incident_summary",
            "send_bob_recommendation_for_approval",
            "push_follow_up_reminders",
            "post_rollback_candidate_alerts",
        ],
        provider_key="slack",
        granted_scopes=[
            "chat:write",
            "chat:write.public",
            "channels:read",
            "users:read",
            "incoming-webhook",
        ],
        downstream_endpoints=[
            "Workspace · Fleetrac Prod",
            "Channel · #ai-governance",
            "Channel · #model-ops-oncall",
        ],
        activity_log=[
            IntegrationActivity(
                at=_ts(0, 2),
                message="Posted Bob recommendation summary for approval (threaded).",
                level="info",
            ),
            IntegrationActivity(
                at=_ts(1, 15),
                message="Incident digest pushed to owner channel.",
                level="info",
            ),
            IntegrationActivity(
                at=_ts(6, 40),
                message="Rollback candidate alert delivered with policy link.",
                level="warn",
            ),
        ],
        audit_log=[
            IntegrationAuditLine(
                at=_ts(240, 0),
                actor="Governance Office",
                summary="Approved Slack app manifest v2 (approval threads).",
            ),
        ],
        bob_prepare_actions=True,
        bob_execute_after_approval=True,
    ),
    Integration(
        id="int_teams",
        provider="Microsoft Teams",
        kind="collaboration",
        connection_status="connected",
        auth_status="token_expiring",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="none",
        config_access="none",
        action_scope="prepare_only",
        last_sync=_ts(0, 45),
        note="Optional Microsoft 365 path for regulated tenants; outbound posts are approval-gated.",
        capabilities=[
            "post_channel_message",
            "post_adaptive_card",
            "read_team_members",
        ],
        provider_key="teams",
        granted_scopes=[
            "ChannelMessage.Send",
            "Team.ReadBasic.All",
            "User.Read.All",
        ],
        downstream_endpoints=["Team · AI Platform · channel Governance alerts"],
        activity_log=[
            IntegrationActivity(
                at=_ts(0, 45),
                message="Adaptive card: awaiting approval for threshold change.",
                level="info",
            ),
        ],
        bob_prepare_actions=True,
        bob_execute_after_approval=False,
    ),
    Integration(
        id="int_pagerduty",
        provider="PagerDuty",
        kind="observability",
        connection_status="connected",
        auth_status="ok",
        sync_status="healthy",
        connector_type="api",
        environments=["production", "staging"],
        telemetry_availability="partial",
        config_access="none",
        action_scope="prepare_only",
        last_sync=_ts(0, 7),
        note="Incident routing metadata and on-call schedules; no direct execute.",
        capabilities=["incidents_read", "schedules_read", "notes_append"],
        provider_key="pagerduty",
        granted_scopes=["incidents:read", "schedules:read", "users:read"],
        downstream_endpoints=["REST Events v2 · governance service"],
        activity_log=[
            IntegrationActivity(
                at=_ts(0, 7),
                message="Synced on-call roster for 6 escalation policies.",
                level="info",
            ),
        ],
        bob_prepare_actions=True,
        bob_execute_after_approval=False,
    ),
]
