import { IncidentQueueTable } from "@/components/incident-queue-table";
import { SectionTitle } from "@/components/ui/section-title";
import { getIncidents } from "@/lib/api";

export default async function IncidentsPage() {
  const { items } = await getIncidents();

  return (
    <section className="space-y-5">
      <SectionTitle
        eyebrow="Triage"
        title="Incident Queue"
        caption="Every incident generated by governance controls. Use filters and sort to focus your team on what matters now."
      />
      <IncidentQueueTable incidents={items} />
    </section>
  );
}
