/**
 * Canonical route builders for Fleetrac.
 *
 * Rationale: every cross-object navigation in the app must land on an exact
 * object, not a generic list. This module is the single source of truth for
 * URL construction so leaf components never hand-assemble routes.
 *
 * All builders return absolute, encoded paths suitable for `<Link href={…}>`
 * or `router.push(…)`. Callers should never prepend/append to the result.
 */

// ---------------------------------------------------------------------------
// Object types
// ---------------------------------------------------------------------------

/** Targets Bob can review (used by the `/bob/for/<type>/<id>` resolver). */
export type BobTargetType = "incident" | "system" | "control";

/** Canonical settings tabs, kept in sync with `SettingsView`. */
export type SettingsTab =
  | "integrations"
  | "policies"
  | "environments"
  | "status"
  | "console";

/** Outcomes view segments — mirrors `SEGMENTS` in `outcomes-view.tsx`. */
export type OutcomesSegment =
  | "all"
  | "monitoring"
  | "improvement"
  | "follow_up"
  | "regression"
  | "closed";

/** Action Center segments — mirrors the server-side whitelist. */
export type ActionSegment =
  | "pending"
  | "ready"
  | "blocked"
  | "executed"
  | "rollback"
  | "closed_rejected";

/** Bob investigation status filter tokens. */
export type BobStatusFilter =
  | "open"
  | "awaiting_approval"
  | "approved"
  | "executed"
  | "closed";

// ---------------------------------------------------------------------------
// Core list pages (canonical parents)
// ---------------------------------------------------------------------------

export const routes = {
  dashboard: () => "/",
  incidents: () => "/incidents",
  activity: () => "/activity",
  systems: () => "/systems",
  controls: () => "/controls",
  actions: () => "/actions",
  outcomes: () => "/outcomes",
  usage: () => "/usage",
  bob: () => "/bob",
  settings: () => "/settings"
} as const;

// ---------------------------------------------------------------------------
// Object detail builders
// ---------------------------------------------------------------------------

export function routeToIncident(id: string): string {
  return `/incidents/${encodeURIComponent(id)}`;
}

export function routeToSystem(id: string): string {
  return `/systems/${encodeURIComponent(id)}`;
}

/** Governance control object detail — operational health, scope, and fleet impact. */
export function routeToControl(id: string): string {
  return `/controls/${encodeURIComponent(id)}`;
}

/** Incident Queue scoped to incidents generated by a governance control (`rule_id`). */
export function routeToIncidentsForControl(controlId: string): string {
  return `/incidents?rule=${encodeURIComponent(controlId)}`;
}

export function routeToAction(id: string): string {
  return `/actions/${encodeURIComponent(id)}`;
}

export function routeToOutcome(id: string): string {
  return `/outcomes/${encodeURIComponent(id)}`;
}

export function routeToBobInvestigation(id: string): string {
  return `/bob/${encodeURIComponent(id)}`;
}

/**
 * Resolver-aware Bob link. Callers without a resolved investigation id route
 * through `/bob/for/<type>/<id>`, which redirects server-side to the exact
 * investigation or to the Bob list with a `missing=` banner.
 *
 * If the caller *does* have an investigation id already, prefer
 * `routeToBobInvestigation(investigationId)` to avoid an unnecessary hop.
 */
export function routeToBobForTarget(
  targetType: BobTargetType,
  targetId: string
): string {
  return `/bob/for/${encodeURIComponent(targetType)}/${encodeURIComponent(targetId)}`;
}

// ---------------------------------------------------------------------------
// Scoped / filtered list builders
// ---------------------------------------------------------------------------

export function routeToIncidentsForSystem(systemId: string): string {
  return `/incidents?system=${encodeURIComponent(systemId)}`;
}

export function routeToOutcomesForSystem(
  systemId: string,
  tab?: OutcomesSegment
): string {
  const qs = new URLSearchParams({ system: systemId });
  if (tab) qs.set("tab", tab);
  return `/outcomes?${qs.toString()}`;
}

export function routeToOutcomesTab(tab: OutcomesSegment): string {
  return `/outcomes?tab=${encodeURIComponent(tab)}`;
}

export function routeToActionsTab(tab: ActionSegment): string {
  return `/actions?tab=${encodeURIComponent(tab)}`;
}

export function routeToBobByStatus(status: BobStatusFilter): string {
  return `/bob?status=${encodeURIComponent(status)}`;
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

export function routeToSettings(
  tab?: SettingsTab,
  options?: { integration?: string }
): string {
  const qs = new URLSearchParams();
  if (tab && tab !== "integrations") {
    qs.set("tab", tab);
  }
  if (options?.integration) {
    qs.set("integration", options.integration);
  }
  const s = qs.toString();
  return s ? `/settings?${s}` : "/settings";
}

/** Deep-link to Integrations with a specific connector detail open. */
export function routeToIntegrationSettings(integrationId: string): string {
  return `/settings?integration=${encodeURIComponent(integrationId)}`;
}

/**
 * Adds a return target to a detail URL so downstream pages can provide
 * context-aware "Back to ..." behavior instead of always falling back to a
 * canonical list page.
 */
export function appendReturnTo(href: string, returnTo?: string | null): string {
  if (!returnTo) return href;
  const [path, qs = ""] = href.split("?");
  const params = new URLSearchParams(qs);
  params.set("returnTo", returnTo);
  const nextQs = params.toString();
  return nextQs ? `${path}?${nextQs}` : path;
}

export function safeReturnTo(
  returnTo: string | null | undefined,
  fallback: string
): string {
  if (!returnTo) return fallback;
  // Only allow in-app absolute paths.
  if (!returnTo.startsWith("/")) return fallback;
  return returnTo;
}

// ---------------------------------------------------------------------------
// Canonical parents (for back-nav fallback)
// ---------------------------------------------------------------------------

/**
 * Every object type maps to a single canonical parent list page. Used as the
 * back-nav fallback when navigation history is unavailable.
 */
export const canonicalParent = {
  incident: () => routes.incidents(),
  activity: () => routes.activity(),
  system: () => routes.systems(),
  control: () => routes.controls(),
  action: () => routes.actions(),
  outcome: () => routes.outcomes(),
  usage: () => routes.usage(),
  bob: () => routes.bob(),
  settings: () => routes.settings()
} as const;

/** True on `/incidents/[id]` (detail), not `/incidents` queue. */
export function isIncidentDetailPath(pathname: string): boolean {
  return /^\/incidents\/[^/]+\/?$/.test(pathname);
}
